---
include:
  - board: nice_nano
    shield: corne_left

  - board: nice_nano
    shield: corne_right

  - board: nice_nano_v2
    shield: corne_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano
    shield: settings_reset
